//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_TestSet : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean HitA
        {
            get
            {
                return SteamVR_Actions.testSet_HitA;
            }
        }
        
        public virtual SteamVR_Action_Boolean HitB
        {
            get
            {
                return SteamVR_Actions.testSet_HitB;
            }
        }
        
        public virtual SteamVR_Action_Boolean HitX
        {
            get
            {
                return SteamVR_Actions.testSet_HitX;
            }
        }
        
        public virtual SteamVR_Action_Boolean HitY
        {
            get
            {
                return SteamVR_Actions.testSet_HitY;
            }
        }
        
        public virtual SteamVR_Action_Boolean DoubleClickA
        {
            get
            {
                return SteamVR_Actions.testSet_DoubleClickA;
            }
        }
    }
}
