//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_CustomSet : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean HitA
        {
            get
            {
                return SteamVR_Actions.customSet_HitA;
            }
        }
        
        public virtual SteamVR_Action_Boolean HitB
        {
            get
            {
                return SteamVR_Actions.customSet_HitB;
            }
        }
        
        public virtual SteamVR_Action_Boolean HitX
        {
            get
            {
                return SteamVR_Actions.customSet_HitX;
            }
        }
        
        public virtual SteamVR_Action_Boolean HitY
        {
            get
            {
                return SteamVR_Actions.customSet_HitY;
            }
        }
        
        public virtual SteamVR_Action_Boolean DoubleClickA
        {
            get
            {
                return SteamVR_Actions.customSet_DoubleClickA;
            }
        }
        
        public virtual SteamVR_Action_Boolean RightTrigger
        {
            get
            {
                return SteamVR_Actions.customSet_RightTrigger;
            }
        }
        
        public virtual SteamVR_Action_Boolean LeftTrigger
        {
            get
            {
                return SteamVR_Actions.customSet_LeftTrigger;
            }
        }
        
        public virtual SteamVR_Action_Vector2 RightJoystick
        {
            get
            {
                return SteamVR_Actions.customSet_RightJoystick;
            }
        }
        
        public virtual SteamVR_Action_Vector2 LeftJoystick
        {
            get
            {
                return SteamVR_Actions.customSet_LeftJoystick;
            }
        }
        
        public virtual SteamVR_Action_Boolean LeftGrip
        {
            get
            {
                return SteamVR_Actions.customSet_LeftGrip;
            }
        }
        
        public virtual SteamVR_Action_Boolean RightGrip
        {
            get
            {
                return SteamVR_Actions.customSet_RightGrip;
            }
        }
    }
}
